### ISSUE TITLE
how to join this Challenge?

### ISSUE THREAD

**Issue by WooXinyi** [IIM-TTIJ/MVA2023SmallObjectDetection4Birds#1]
how to join this Challenge? I cannot find the competition in codalab.

**Comment by IIM-TTIJ** [comment]
Dear WooXinyi,

Thank you for your interest in our competition!

The competition is currently not open, and the CodaLab site has not been released yet, and the CodaLab site will be released on 2023-1-9.

Detailed dates and updates on this competition are available on the official MVA2023 website. Please check it out.
http://www.mva-org.jp/mva2023/challenge

After the CodaLab competition site is released, we will add the URL to the ReadMe of this repository.

Best Regards,

**Comment by Yuki-11** [comment]
Dear @WooXinyi ,

I hope you are having a good weekend.

I am happy to tell you that this Challenge has begun.
You can register to participate in our Challenge at the following URL.
https://codalab.lisn.upsaclay.fr/competitions/9594

We look forward to your participation.

Regards,
